### ISSUE TITLE
FE - Authentication Page

### ISSUE THREAD

**Issue by Lucas-Martin2023** [ndswimming92/disaster-relief-e22-e24#2]
# USER STORY
- [ ] As a user, who is logged out, I should only be able to see the authentication screen
- [ ] As a user who is logged out, I would like to be able to click on an authentication button and login via google.

# DEV NOTES
![image](https://github.com/Lucas-Martin2023/INDIVIDUAL-ASSIGNMENT-Team-Roster/assets/135672846/36861d17-5358-41ee-ae31-cad5c585e044)

**Comment by SteveCButler** [comment]
authentication has been setup and tested
